# Generated by Django 6.0.1 on 2026-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('letter_count', models.PositiveIntegerField()),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='words', to='dictionary.category')),
            ],
        ),
    ]
